### ISSUE TITLE
Issue with drop down component

### ISSUE THREAD

**Issue by AshishBhalala** [turtlemint/mint-ui#4]
Type '{ children: any; key: any; value: any; }' is not assignable to type 'IntrinsicAttributes & DropdownProps'.
  Property 'value' does not exist on type 'IntrinsicAttributes & DropdownProps'

`<Select value="Test value">
	{data.map((d: any) => (
		<Option key={d.key} value={d.val}>
			{d.displayName}
	         </Option>
	))}
</Select>`

**Comment by kushalmahajan** [comment]
Hi Ashish,

Please mention which version of `mint-ui` you are using.
It would be great if you share a reproducible link to same, maybe on code https://codesandbox.io/?

**Comment by kushalmahajan** [comment]
I have demonstrated a working example for version `1.0.2`  - https://codesandbox.io/s/jovial-lamport-11fmc

I feel documentation for imports is missing from our storybook site so far. This won't be an issue once we move completely to a new documentation site. Thanks!

Closing this issue. If you face any challenge, feel free to discuss it.
